services:
  account_service:
    build: ./account-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./account-service/:/app/
    ports:
      - 8001:8000

  transaction_service:
    build: ./transaction-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./transaction-service/:/app/
    ports:
      - 8002:8000

  db:
    image: postgres:14.8-alpine3.18
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    
  nginx:
      image: nginx:latest
      ports:
        - "8080:8080"
      volumes:
        - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - account_service
        - transaction_service

volumes:
  postgres_data: