"""fs

Revision ID: 56fce2ec5dc8
Revises: 
Create Date: 2025-01-24 12:56:45.298659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56fce2ec5dc8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('currency_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('sender_id', sa.BigInteger(), nullable=True),
    sa.Column('receiver_id', sa.BigInteger(), nullable=True),
    sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', postgresql.ENUM('Cancelled', 'Pending', 'Successful', name='transaction_status_enum'), nullable=False),
    sa.Column('type', postgresql.ENUM('Transfer', 'Payment', 'Withdrawal', 'Deposit', name='operation_type_enum'), nullable=False),
    sa.Column('sender_balance', sa.Numeric(), nullable=True),
    sa.Column('receiver_balance', sa.Numeric(), nullable=True),
    sa.Column('mcc', sa.SmallInteger(), nullable=True),
    sa.Column('fee', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('account')
    op.drop_table('currency')
    # ### end Alembic commands ###
